configs:
  wiki_config:
    file: $PWD/Caddyfile.wiki
  hupi_config:
    file: $PWD/Caddyfile.hupi
  
volumes:
  app:
    name: wiki-app
  images:
    name: wiki-images
  database:
    name: wiki-db

services:
  wiki:
    image: caddy:latest
    environment:
      TZ: 'America/Los_Angeles'
    configs:
      - source: wiki_config
        target: /etc/caddy/Caddyfile
    volumes:
#      - ./Caddyfile.wiki:/etc/caddy/Caddyfile
      - app:/srv/wiki:ro
      - images:/srv/wiki/images:rw
    ports:
      - 81:80
    restart: unless-stopped
    depends_on:
      - phpfpm

  hupi:
    image: caddy:latest
    environment:
      TZ: 'America/Los_Angeles'
    configs:
      - source: hupi_config
        target: /etc/caddy/Caddyfile
    volumes:
#      - ./Caddyfile.hupi:/etc/caddy/Caddyfile:ro
      - /home/hupi/content:/srv/hupi:ro #### content to be served
    ports:
      - 82:80

  phpfpm:
    image: phpfpm
    build: 
      context: .
      dockerfile: Dockerfile.phpfpm
    volumes:
      - ./php-fpm.d:/usr/local/etc/php-fpm.d:ro
      - app:/srv/wiki:ro
      - images:/srv/wiki/images:rw
      - /home/hupi/content:/srv/hupi:ro
    restart: unless-stopped

  database:
    container_name: wikidb
    image: mariadb:latest
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - database:/var/lib/mysql
